CREATE TABLE skills (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  category ENUM('programming','devops','cloud','ai_ml','design','business','languages','finance','productivity','career')
);

-- Seed data: common skills across categories
INSERT INTO skills (name, category) VALUES
  ('JavaScript', 'programming'),
  ('TypeScript', 'programming'),
  ('Python', 'programming'),
  ('Java', 'programming'),
  ('C#', 'programming'),
  ('Go', 'programming'),
  ('Rust', 'programming'),
  ('Ruby', 'programming'),
  ('PHP', 'programming'),
  ('Swift', 'programming'),
  ('Kotlin', 'programming'),
  ('C++', 'programming'),
  ('React', 'programming'),
  ('Angular', 'programming'),
  ('Vue.js', 'programming'),
  ('Node.js', 'programming'),
  ('Django', 'programming'),
  ('Spring Boot', 'programming'),
  ('Flutter', 'programming'),
  ('React Native', 'programming'),
  ('Docker', 'devops'),
  ('Kubernetes', 'devops'),
  ('CI/CD Pipelines', 'devops'),
  ('Terraform', 'devops'),
  ('Ansible', 'devops'),
  ('Jenkins', 'devops'),
  ('GitHub Actions', 'devops'),
  ('Linux Administration', 'devops'),
  ('AWS', 'cloud'),
  ('Azure', 'cloud'),
  ('Google Cloud Platform', 'cloud'),
  ('Serverless Architecture', 'cloud'),
  ('Cloud Security', 'cloud'),
  ('Machine Learning', 'ai_ml'),
  ('Deep Learning', 'ai_ml'),
  ('Natural Language Processing', 'ai_ml'),
  ('Computer Vision', 'ai_ml'),
  ('TensorFlow', 'ai_ml'),
  ('PyTorch', 'ai_ml'),
  ('Data Science', 'ai_ml'),
  ('UI/UX Design', 'design'),
  ('Figma', 'design'),
  ('Adobe Photoshop', 'design'),
  ('Graphic Design', 'design'),
  ('Web Design', 'design'),
  ('Product Management', 'business'),
  ('Agile/Scrum', 'business'),
  ('Business Analysis', 'business'),
  ('Marketing Strategy', 'business'),
  ('Project Management', 'business'),
  ('English', 'languages'),
  ('Spanish', 'languages'),
  ('Mandarin', 'languages'),
  ('French', 'languages'),
  ('German', 'languages'),
  ('Japanese', 'languages'),
  ('Financial Modeling', 'finance'),
  ('Cryptocurrency', 'finance'),
  ('Investment Analysis', 'finance'),
  ('Accounting', 'finance'),
  ('Time Management', 'productivity'),
  ('Public Speaking', 'productivity'),
  ('Technical Writing', 'productivity'),
  ('Problem Solving', 'productivity'),
  ('Resume Building', 'career'),
  ('Interview Preparation', 'career'),
  ('Networking', 'career'),
  ('Career Transition', 'career');
